with-expecter: true
dir: "{{.InterfaceDir}}/mocks/"
outpkg: "mocks"
packages:
  github.com/petrenko-alex/api-rate-limiter/internal/ipnet:
    interfaces:
      IRuleStorage:
  github.com/petrenko-alex/api-rate-limiter/internal/limiter:
    interfaces:
      ILimitStorage: