// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.6.1
// source: api/RateLimiter.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WhiteListAddRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IpNet *IPNet `protobuf:"bytes,1,opt,name=ip_net,json=ipNet,proto3" json:"ip_net,omitempty"`
}

func (x *WhiteListAddRequest) Reset() {
	*x = WhiteListAddRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_RateLimiter_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WhiteListAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhiteListAddRequest) ProtoMessage() {}

func (x *WhiteListAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_RateLimiter_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhiteListAddRequest.ProtoReflect.Descriptor instead.
func (*WhiteListAddRequest) Descriptor() ([]byte, []int) {
	return file_api_RateLimiter_proto_rawDescGZIP(), []int{0}
}

func (x *WhiteListAddRequest) GetIpNet() *IPNet {
	if x != nil {
		return x.IpNet
	}
	return nil
}

type WhiteListDeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IpNet *IPNet `protobuf:"bytes,1,opt,name=ip_net,json=ipNet,proto3" json:"ip_net,omitempty"`
}

func (x *WhiteListDeleteRequest) Reset() {
	*x = WhiteListDeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_RateLimiter_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WhiteListDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhiteListDeleteRequest) ProtoMessage() {}

func (x *WhiteListDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_RateLimiter_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhiteListDeleteRequest.ProtoReflect.Descriptor instead.
func (*WhiteListDeleteRequest) Descriptor() ([]byte, []int) {
	return file_api_RateLimiter_proto_rawDescGZIP(), []int{1}
}

func (x *WhiteListDeleteRequest) GetIpNet() *IPNet {
	if x != nil {
		return x.IpNet
	}
	return nil
}

type BlackListAddRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IpNet *IPNet `protobuf:"bytes,1,opt,name=ip_net,json=ipNet,proto3" json:"ip_net,omitempty"`
}

func (x *BlackListAddRequest) Reset() {
	*x = BlackListAddRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_RateLimiter_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlackListAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlackListAddRequest) ProtoMessage() {}

func (x *BlackListAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_RateLimiter_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlackListAddRequest.ProtoReflect.Descriptor instead.
func (*BlackListAddRequest) Descriptor() ([]byte, []int) {
	return file_api_RateLimiter_proto_rawDescGZIP(), []int{2}
}

func (x *BlackListAddRequest) GetIpNet() *IPNet {
	if x != nil {
		return x.IpNet
	}
	return nil
}

type BlackListDeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IpNet *IPNet `protobuf:"bytes,1,opt,name=ip_net,json=ipNet,proto3" json:"ip_net,omitempty"`
}

func (x *BlackListDeleteRequest) Reset() {
	*x = BlackListDeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_RateLimiter_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlackListDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlackListDeleteRequest) ProtoMessage() {}

func (x *BlackListDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_RateLimiter_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlackListDeleteRequest.ProtoReflect.Descriptor instead.
func (*BlackListDeleteRequest) Descriptor() ([]byte, []int) {
	return file_api_RateLimiter_proto_rawDescGZIP(), []int{3}
}

func (x *BlackListDeleteRequest) GetIpNet() *IPNet {
	if x != nil {
		return x.IpNet
	}
	return nil
}

type BucketResetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Login string `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Ip    string `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
}

func (x *BucketResetRequest) Reset() {
	*x = BucketResetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_RateLimiter_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BucketResetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BucketResetRequest) ProtoMessage() {}

func (x *BucketResetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_RateLimiter_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BucketResetRequest.ProtoReflect.Descriptor instead.
func (*BucketResetRequest) Descriptor() ([]byte, []int) {
	return file_api_RateLimiter_proto_rawDescGZIP(), []int{4}
}

func (x *BucketResetRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *BucketResetRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type LimitCheckRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Login    string `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Ip       string `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
}

func (x *LimitCheckRequest) Reset() {
	*x = LimitCheckRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_RateLimiter_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LimitCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LimitCheckRequest) ProtoMessage() {}

func (x *LimitCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_RateLimiter_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LimitCheckRequest.ProtoReflect.Descriptor instead.
func (*LimitCheckRequest) Descriptor() ([]byte, []int) {
	return file_api_RateLimiter_proto_rawDescGZIP(), []int{5}
}

func (x *LimitCheckRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *LimitCheckRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LimitCheckRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type WhiteListAddResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *WhiteListAddResponse) Reset() {
	*x = WhiteListAddResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_RateLimiter_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WhiteListAddResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhiteListAddResponse) ProtoMessage() {}

func (x *WhiteListAddResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_RateLimiter_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhiteListAddResponse.ProtoReflect.Descriptor instead.
func (*WhiteListAddResponse) Descriptor() ([]byte, []int) {
	return file_api_RateLimiter_proto_rawDescGZIP(), []int{6}
}

type WhiteListDeleteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *WhiteListDeleteResponse) Reset() {
	*x = WhiteListDeleteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_RateLimiter_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WhiteListDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhiteListDeleteResponse) ProtoMessage() {}

func (x *WhiteListDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_RateLimiter_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhiteListDeleteResponse.ProtoReflect.Descriptor instead.
func (*WhiteListDeleteResponse) Descriptor() ([]byte, []int) {
	return file_api_RateLimiter_proto_rawDescGZIP(), []int{7}
}

type BlackListAddResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BlackListAddResponse) Reset() {
	*x = BlackListAddResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_RateLimiter_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlackListAddResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlackListAddResponse) ProtoMessage() {}

func (x *BlackListAddResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_RateLimiter_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlackListAddResponse.ProtoReflect.Descriptor instead.
func (*BlackListAddResponse) Descriptor() ([]byte, []int) {
	return file_api_RateLimiter_proto_rawDescGZIP(), []int{8}
}

type BlackListDeleteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BlackListDeleteResponse) Reset() {
	*x = BlackListDeleteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_RateLimiter_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlackListDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlackListDeleteResponse) ProtoMessage() {}

func (x *BlackListDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_RateLimiter_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlackListDeleteResponse.ProtoReflect.Descriptor instead.
func (*BlackListDeleteResponse) Descriptor() ([]byte, []int) {
	return file_api_RateLimiter_proto_rawDescGZIP(), []int{9}
}

type BucketResetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BucketResetResponse) Reset() {
	*x = BucketResetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_RateLimiter_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BucketResetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BucketResetResponse) ProtoMessage() {}

func (x *BucketResetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_RateLimiter_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BucketResetResponse.ProtoReflect.Descriptor instead.
func (*BucketResetResponse) Descriptor() ([]byte, []int) {
	return file_api_RateLimiter_proto_rawDescGZIP(), []int{10}
}

type LimitCheckResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Allowed bool `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
}

func (x *LimitCheckResponse) Reset() {
	*x = LimitCheckResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_RateLimiter_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LimitCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LimitCheckResponse) ProtoMessage() {}

func (x *LimitCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_RateLimiter_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LimitCheckResponse.ProtoReflect.Descriptor instead.
func (*LimitCheckResponse) Descriptor() ([]byte, []int) {
	return file_api_RateLimiter_proto_rawDescGZIP(), []int{11}
}

func (x *LimitCheckResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

type IPNet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ip   string `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Mask string `protobuf:"bytes,2,opt,name=mask,proto3" json:"mask,omitempty"`
}

func (x *IPNet) Reset() {
	*x = IPNet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_RateLimiter_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IPNet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPNet) ProtoMessage() {}

func (x *IPNet) ProtoReflect() protoreflect.Message {
	mi := &file_api_RateLimiter_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPNet.ProtoReflect.Descriptor instead.
func (*IPNet) Descriptor() ([]byte, []int) {
	return file_api_RateLimiter_proto_rawDescGZIP(), []int{12}
}

func (x *IPNet) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *IPNet) GetMask() string {
	if x != nil {
		return x.Mask
	}
	return ""
}

var File_api_RateLimiter_proto protoreflect.FileDescriptor

var file_api_RateLimiter_proto_rawDesc = []byte{
	0x0a, 0x15, 0x61, 0x70, 0x69, 0x2f, 0x52, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x52, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x6d,
	0x69, 0x74, 0x65, 0x72, 0x22, 0x40, 0x0a, 0x13, 0x57, 0x68, 0x69, 0x74, 0x65, 0x4c, 0x69, 0x73,
	0x74, 0x41, 0x64, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x29, 0x0a, 0x06, 0x69,
	0x70, 0x5f, 0x6e, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x52, 0x61,
	0x74, 0x65, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x65, 0x72, 0x2e, 0x49, 0x50, 0x4e, 0x65, 0x74, 0x52,
	0x05, 0x69, 0x70, 0x4e, 0x65, 0x74, 0x22, 0x43, 0x0a, 0x16, 0x57, 0x68, 0x69, 0x74, 0x65, 0x4c,
	0x69, 0x73, 0x74, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x29, 0x0a, 0x06, 0x69, 0x70, 0x5f, 0x6e, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x12, 0x2e, 0x52, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x65, 0x72, 0x2e, 0x49,
	0x50, 0x4e, 0x65, 0x74, 0x52, 0x05, 0x69, 0x70, 0x4e, 0x65, 0x74, 0x22, 0x40, 0x0a, 0x13, 0x42,
	0x6c, 0x61, 0x63, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x64, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x29, 0x0a, 0x06, 0x69, 0x70, 0x5f, 0x6e, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x12, 0x2e, 0x52, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x65, 0x72,
	0x2e, 0x49, 0x50, 0x4e, 0x65, 0x74, 0x52, 0x05, 0x69, 0x70, 0x4e, 0x65, 0x74, 0x22, 0x43, 0x0a,
	0x16, 0x42, 0x6c, 0x61, 0x63, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x29, 0x0a, 0x06, 0x69, 0x70, 0x5f, 0x6e, 0x65,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x52, 0x61, 0x74, 0x65, 0x4c, 0x69,
	0x6d, 0x69, 0x74, 0x65, 0x72, 0x2e, 0x49, 0x50, 0x4e, 0x65, 0x74, 0x52, 0x05, 0x69, 0x70, 0x4e,
	0x65, 0x74, 0x22, 0x3a, 0x0a, 0x12, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x73, 0x65,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x6f, 0x67, 0x69,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x22, 0x55,
	0x0a, 0x11, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73,
	0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73,
	0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x70, 0x22, 0x16, 0x0a, 0x14, 0x57, 0x68, 0x69, 0x74, 0x65, 0x4c, 0x69,
	0x73, 0x74, 0x41, 0x64, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x19, 0x0a,
	0x17, 0x57, 0x68, 0x69, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x16, 0x0a, 0x14, 0x42, 0x6c, 0x61, 0x63,
	0x6b, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x64, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x19, 0x0a, 0x17, 0x42, 0x6c, 0x61, 0x63, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x15, 0x0a, 0x13, 0x42,
	0x75, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x73, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x2e, 0x0a, 0x12, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x43, 0x68, 0x65, 0x63, 0x6b,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x6c, 0x6c, 0x6f,
	0x77, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x61, 0x6c, 0x6c, 0x6f, 0x77,
	0x65, 0x64, 0x22, 0x2b, 0x0a, 0x05, 0x49, 0x50, 0x4e, 0x65, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x6d,
	0x61, 0x73, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6d, 0x61, 0x73, 0x6b, 0x32,
	0xa0, 0x04, 0x0a, 0x0b, 0x52, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x65, 0x72, 0x12,
	0x55, 0x0a, 0x0c, 0x57, 0x68, 0x69, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x64, 0x64, 0x12,
	0x20, 0x2e, 0x52, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x65, 0x72, 0x2e, 0x57, 0x68,
	0x69, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x64, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x21, 0x2e, 0x52, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x65, 0x72, 0x2e,
	0x57, 0x68, 0x69, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x64, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5e, 0x0a, 0x0f, 0x57, 0x68, 0x69, 0x74, 0x65, 0x4c,
	0x69, 0x73, 0x74, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x23, 0x2e, 0x52, 0x61, 0x74, 0x65,
	0x4c, 0x69, 0x6d, 0x69, 0x74, 0x65, 0x72, 0x2e, 0x57, 0x68, 0x69, 0x74, 0x65, 0x4c, 0x69, 0x73,
	0x74, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24,
	0x2e, 0x52, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x65, 0x72, 0x2e, 0x57, 0x68, 0x69,
	0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x55, 0x0a, 0x0c, 0x42, 0x6c, 0x61, 0x63, 0x6b, 0x4c,
	0x69, 0x73, 0x74, 0x41, 0x64, 0x64, 0x12, 0x20, 0x2e, 0x52, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x6d,
	0x69, 0x74, 0x65, 0x72, 0x2e, 0x42, 0x6c, 0x61, 0x63, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x64,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x52, 0x61, 0x74, 0x65, 0x4c,
	0x69, 0x6d, 0x69, 0x74, 0x65, 0x72, 0x2e, 0x42, 0x6c, 0x61, 0x63, 0x6b, 0x4c, 0x69, 0x73, 0x74,
	0x41, 0x64, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5e, 0x0a,
	0x0f, 0x42, 0x6c, 0x61, 0x63, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x12, 0x23, 0x2e, 0x52, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x65, 0x72, 0x2e, 0x42,
	0x6c, 0x61, 0x63, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x52, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x6d, 0x69,
	0x74, 0x65, 0x72, 0x2e, 0x42, 0x6c, 0x61, 0x63, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x52, 0x0a,
	0x0b, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x73, 0x65, 0x74, 0x12, 0x1f, 0x2e, 0x52,
	0x61, 0x74, 0x65, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x65, 0x72, 0x2e, 0x42, 0x75, 0x63, 0x6b, 0x65,
	0x74, 0x52, 0x65, 0x73, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e,
	0x52, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x65, 0x72, 0x2e, 0x42, 0x75, 0x63, 0x6b,
	0x65, 0x74, 0x52, 0x65, 0x73, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x4f, 0x0a, 0x0a, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x12,
	0x1e, 0x2e, 0x52, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x65, 0x72, 0x2e, 0x4c, 0x69,
	0x6d, 0x69, 0x74, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1f, 0x2e, 0x52, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x65, 0x72, 0x2e, 0x4c, 0x69,
	0x6d, 0x69, 0x74, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x42, 0x31, 0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x70, 0x65, 0x74, 0x72, 0x65, 0x6e, 0x6b, 0x6f, 0x2d, 0x61, 0x6c, 0x65, 0x78, 0x2f, 0x61,
	0x70, 0x69, 0x2d, 0x72, 0x61, 0x74, 0x65, 0x2d, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x65, 0x72, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_RateLimiter_proto_rawDescOnce sync.Once
	file_api_RateLimiter_proto_rawDescData = file_api_RateLimiter_proto_rawDesc
)

func file_api_RateLimiter_proto_rawDescGZIP() []byte {
	file_api_RateLimiter_proto_rawDescOnce.Do(func() {
		file_api_RateLimiter_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_RateLimiter_proto_rawDescData)
	})
	return file_api_RateLimiter_proto_rawDescData
}

var file_api_RateLimiter_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_api_RateLimiter_proto_goTypes = []interface{}{
	(*WhiteListAddRequest)(nil),     // 0: RateLimiter.WhiteListAddRequest
	(*WhiteListDeleteRequest)(nil),  // 1: RateLimiter.WhiteListDeleteRequest
	(*BlackListAddRequest)(nil),     // 2: RateLimiter.BlackListAddRequest
	(*BlackListDeleteRequest)(nil),  // 3: RateLimiter.BlackListDeleteRequest
	(*BucketResetRequest)(nil),      // 4: RateLimiter.BucketResetRequest
	(*LimitCheckRequest)(nil),       // 5: RateLimiter.LimitCheckRequest
	(*WhiteListAddResponse)(nil),    // 6: RateLimiter.WhiteListAddResponse
	(*WhiteListDeleteResponse)(nil), // 7: RateLimiter.WhiteListDeleteResponse
	(*BlackListAddResponse)(nil),    // 8: RateLimiter.BlackListAddResponse
	(*BlackListDeleteResponse)(nil), // 9: RateLimiter.BlackListDeleteResponse
	(*BucketResetResponse)(nil),     // 10: RateLimiter.BucketResetResponse
	(*LimitCheckResponse)(nil),      // 11: RateLimiter.LimitCheckResponse
	(*IPNet)(nil),                   // 12: RateLimiter.IPNet
}
var file_api_RateLimiter_proto_depIdxs = []int32{
	12, // 0: RateLimiter.WhiteListAddRequest.ip_net:type_name -> RateLimiter.IPNet
	12, // 1: RateLimiter.WhiteListDeleteRequest.ip_net:type_name -> RateLimiter.IPNet
	12, // 2: RateLimiter.BlackListAddRequest.ip_net:type_name -> RateLimiter.IPNet
	12, // 3: RateLimiter.BlackListDeleteRequest.ip_net:type_name -> RateLimiter.IPNet
	0,  // 4: RateLimiter.RateLimiter.WhiteListAdd:input_type -> RateLimiter.WhiteListAddRequest
	1,  // 5: RateLimiter.RateLimiter.WhiteListDelete:input_type -> RateLimiter.WhiteListDeleteRequest
	2,  // 6: RateLimiter.RateLimiter.BlackListAdd:input_type -> RateLimiter.BlackListAddRequest
	3,  // 7: RateLimiter.RateLimiter.BlackListDelete:input_type -> RateLimiter.BlackListDeleteRequest
	4,  // 8: RateLimiter.RateLimiter.BucketReset:input_type -> RateLimiter.BucketResetRequest
	5,  // 9: RateLimiter.RateLimiter.LimitCheck:input_type -> RateLimiter.LimitCheckRequest
	6,  // 10: RateLimiter.RateLimiter.WhiteListAdd:output_type -> RateLimiter.WhiteListAddResponse
	7,  // 11: RateLimiter.RateLimiter.WhiteListDelete:output_type -> RateLimiter.WhiteListDeleteResponse
	8,  // 12: RateLimiter.RateLimiter.BlackListAdd:output_type -> RateLimiter.BlackListAddResponse
	9,  // 13: RateLimiter.RateLimiter.BlackListDelete:output_type -> RateLimiter.BlackListDeleteResponse
	10, // 14: RateLimiter.RateLimiter.BucketReset:output_type -> RateLimiter.BucketResetResponse
	11, // 15: RateLimiter.RateLimiter.LimitCheck:output_type -> RateLimiter.LimitCheckResponse
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_api_RateLimiter_proto_init() }
func file_api_RateLimiter_proto_init() {
	if File_api_RateLimiter_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_RateLimiter_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WhiteListAddRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_RateLimiter_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WhiteListDeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_RateLimiter_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlackListAddRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_RateLimiter_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlackListDeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_RateLimiter_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BucketResetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_RateLimiter_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LimitCheckRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_RateLimiter_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WhiteListAddResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_RateLimiter_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WhiteListDeleteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_RateLimiter_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlackListAddResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_RateLimiter_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlackListDeleteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_RateLimiter_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BucketResetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_RateLimiter_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LimitCheckResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_RateLimiter_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IPNet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_RateLimiter_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_RateLimiter_proto_goTypes,
		DependencyIndexes: file_api_RateLimiter_proto_depIdxs,
		MessageInfos:      file_api_RateLimiter_proto_msgTypes,
	}.Build()
	File_api_RateLimiter_proto = out.File
	file_api_RateLimiter_proto_rawDesc = nil
	file_api_RateLimiter_proto_goTypes = nil
	file_api_RateLimiter_proto_depIdxs = nil
}
