name: main
on: [pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3.7.0
        with:
          version: v1.54.2

  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Testing..."
